### ISSUE TITLE
Bug: `ccxt` is not optional as per the documentation.

### ISSUE THREAD

**Issue by YasserHassan** [tensortrade-org/tensortrade#138]
This is not exactly a bug but still causes an error and inconsistent with the documentation. The documentation mentions that `ccxt` is an optional dependency in the Installation section. However, if `ccxt` is not installed, an error is produced when importing `SimulatedExchange`.

Running:
```
from tensortrade.exchanges.simulated import SimulatedExchange
```
Gives:
> ...
> ModuleNotFoundError: No module named 'ccxt'

**Comment by notadamking** [comment]
This has been fixed.

**Comment by gvossos** [comment]
I'm still getting this error wih tensortrade 0.2.0b2.

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-ba647e4ff1fd> in <module>
      1 import ccxt
----> 2 from tensortrade.exchanges.simulated import SimulatedExchange
      3 
      4 df = pd.read_csv('data/Coinbase_BTCUSD_1h.csv', skiprows=1)
      5 exchange = SimulatedExchange(data_frame=df, base_instrument='USD', pretransform=True)

ModuleNotFoundError: No module named 'tensortrade.exchanges.simulated'

**Comment by naths84** [comment]
Getting the same error too.
