### ISSUE TITLE
Error occurs when running latest ray example

### ISSUE THREAD

**Issue by yglpyn8888** [tensortrade-org/tensortrade#361]
in this demo, https://github.com/tensortrade-org/tensortrade/blob/master/docs/source/examples/train_and_evaluate_using_ray.md
when it comes to this lineL
"df_training = yf_ticker.history(start=START_DATE, end=END_DATE, interval='60m')"
it raises a JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yglpyn8888** [comment]
and why the STARTDATE and ENDDATE in which df_training/df_evaluation uses are the same?

**Comment by carlogrisetti** [comment]
As per the JSONDecodeError, what symbol are you using? I suspect you left the TTRD fake symbol in there.

I fixed the startdate\enddatre thing... it was a copypasta :)

**Comment by yglpyn8888** [comment]
after i use real symbol ,still the same error...
i tried "AAPL","aapl","MSFT",""msft"...

**Comment by carlogrisetti** [comment]
Can you share the code you are running?
This could however be more suited for asking to yfinance developers, since it's the basic method call to their library.

**Comment by yglpyn8888** [comment]
i also think it is a network problem,  i closed this issue.
